server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#打印sql
logging:
  level:
    com.summer.dao: debug
#mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
